services:
  # FASE 1: Aplikasi
  # a. 1 container khusus untuk web application, di dalam container ini memiliki aplikasi default Yii 2.0 
  web-app:
    build: ./web              # Membangun image dari Dockerfile 
    container_name: yii-app   
  #  ports:
  #    - "3000:3000"           # Mapping Port Host:Container 
    depends_on:
      - db                    
    networks:
      - dhealth-net

  # b. 1 container khusus untuk database PostgreSQL
  db:
    image: postgres:16   
    container_name: postgres-db
    environment:
      POSTGRES_DB: ${DB_NAME:-yii2basic}  
      POSTGRES_USER: ${DB_USER:-dhealth_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-dhealth_secure_pass}
    volumes:
      - ./db-data:/var/lib/postgresql/data # Volume mapping 
    networks:
      - dhealth-net


  # FASE 2: Reverse Proxy Nginx

  nginx:
    image : nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web-app
    networks:
      - dhealth-net


  # FASE 3: Monitoring dengan Prometheus dan Node Exporter

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    command:
      - '--path.rootfs=/host'        # 1. Beritahu Node Exporter bahwa root ada di folder /host
    volumes:
      - /:/host:ro
    networks:
      - dhealth-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - node-exporter
    networks:
      - dhealth-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    networks:
      - dhealth-net

# Mendefinisikan Network agar kedua container bisa saling komunikasi
networks:
  dhealth-net:
    driver: bridge