services:
  # FASE 1
  web-app:
    build: ./web              
    container_name: yii-app   
  #  ports:
  #    - "3000:3000"           
    depends_on:
      - db                    
    networks:
      - dhealth-net

  db:
    image: postgres:16   
    container_name: postgres-db
    environment:
      POSTGRES_DB: ${DB_NAME:-yii2basic}  
      POSTGRES_USER: ${DB_USER:-dhealth_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-dhealth_secure_pass}
    volumes:
      - ./db-data:/var/lib/postgresql/data 
    networks:
      - dhealth-net


  # FASE 2
  nginx:
    image : nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web-app
    networks:
      - dhealth-net


  # FASE 3:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    command:
      - '--path.rootfs=/host'        
    volumes:
      - /:/host:ro
    networks:
      - dhealth-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - node-exporter
    networks:
      - dhealth-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    networks:
      - dhealth-net

networks:
  dhealth-net:
    driver: bridge