services:
  # FASE 1
  web-app:
    build: ./web              
    container_name: yii-app   
  #  ports:
  #    - "3000:3000"           
    depends_on:
      - db                    
    networks:
      - dhealth-net

  db:
    image: postgres:16   
    container_name: postgres-db
    environment:
      POSTGRES_DB: ${DB_NAME:-yii2basic}  
      POSTGRES_USER: ${DB_USER:-dhealth_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-dhealth_secure_pass}
    volumes:
      - ./db-data:/var/lib/postgresql/data 
    networks:
      - dhealth-net


# FASE 2
  nginx:
    image : nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web-app
    networks:
      - dhealth-net

networks:
  dhealth-net:
    driver: bridge